name: express-api-test

services:
  express:
    container_name: express
    build:
      context: ./
      dockerfile: Dockerfile.test
    env_file:
      - ./.env
    ports:
      - 3000:${APP_PORT}
      - 9229:9229
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:${DB_PORT}
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data_test:
